ALTER TABLE "laboratory"
ADD COLUMN "workingDays" TEXT[] NOT NULL DEFAULT ARRAY['SATURDAY', 'SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY']::TEXT[],
ADD COLUMN "opensAt" TEXT NOT NULL DEFAULT '10:00',
ADD COLUMN "closesAt" TEXT NOT NULL DEFAULT '20:00';
