export const laboratorySeedData = [
  {
    id: 'alpha-diagnostics',
    name: 'Alpha Diagnostics',
    shortName: 'AD',
    city: 'Cairo',
    area: 'Nasr City',
    address: '18 Abbas El Akkad Street, Nasr City, Cairo',
    phone: '+20 2 2401 8810',
    rating: 4.9,
    reviewCount: 428,
    accreditation: 'ISO 15189 accredited',
    turnaround: 'Results from 2 hours',
    tone: 'emerald',
    about:
      'Alpha Diagnostics combines modern laboratory technology with careful clinical review. Its Nasr City branch provides routine testing, preventive health packages, and specialized diagnostics in a calm, accessible setting.',
    facilities: [
      'Home sample collection',
      'Digital results',
      'Wheelchair access',
    ],
    services: [
      [
        'alpha-cbc',
        'Complete Blood Count',
        'A complete review of red cells, white cells, and platelets.',
        260,
        '2 hours',
        'No fasting required',
      ],
      [
        'alpha-liver',
        'Liver Function Profile',
        'Key enzymes and proteins used to assess liver health.',
        520,
        'Same day',
        'Fasting preferred',
        true,
      ],
      [
        'alpha-thyroid',
        'Thyroid Profile',
        'TSH, free T3, and free T4 hormone assessment.',
        680,
        'Same day',
        'No fasting required',
      ],
      [
        'alpha-checkup',
        'Essential Health Check',
        'CBC, glucose, liver, kidney, and lipid screening package.',
        1450,
        '24 hours',
        '8-10 hours fasting',
        true,
      ],
    ],
    reviews: [
      [
        'alpha-review-1',
        'Mariam Hassan',
        5,
        'The staff explained the fasting instructions clearly and my results arrived earlier than expected.',
        '2026-07-27T10:30:00.000Z',
      ],
      [
        'alpha-review-2',
        'Omar Adel',
        5,
        'Very clean branch, quick registration, and the digital report was easy to understand.',
        '2026-07-18T16:15:00.000Z',
      ],
    ],
  },
  {
    id: 'nile-medical-labs',
    name: 'Nile Medical Labs',
    shortName: 'NL',
    city: 'Giza',
    area: 'Dokki',
    address: '42 Mossadak Street, Dokki, Giza',
    phone: '+20 2 3762 4190',
    rating: 4.8,
    reviewCount: 315,
    accreditation: 'CAP quality standards',
    turnaround: 'Results from 3 hours',
    tone: 'teal',
    about:
      'Nile Medical Labs is a neighborhood diagnostics center known for clear guidance, dependable results, and a broad menu of routine and advanced tests.',
    facilities: ['Home sample collection', 'Online reports', 'Family packages'],
    services: [
      [
        'nile-diabetes',
        'Diabetes Screening',
        'Fasting glucose and HbA1c for long-term blood sugar assessment.',
        410,
        'Same day',
        '8 hours fasting',
        true,
      ],
      [
        'nile-kidney',
        'Kidney Function Profile',
        'Creatinine, urea, and electrolyte testing.',
        480,
        'Same day',
        'No special preparation',
      ],
      [
        'nile-vitamin',
        'Vitamin D Test',
        'Measures vitamin D levels to support bone and immune health.',
        790,
        '24 hours',
        'No fasting required',
      ],
      [
        'nile-wellness',
        'Complete Wellness Package',
        'A broad preventive panel covering blood, liver, kidney, thyroid, and vitamins.',
        1850,
        '24 hours',
        '8-10 hours fasting',
        true,
      ],
    ],
    reviews: [
      [
        'nile-review-1',
        'Salma Tarek',
        5,
        'A smooth experience from reception to sample collection. Everyone was kind and professional.',
        '2026-07-24T12:00:00.000Z',
      ],
      [
        'nile-review-2',
        'Ahmed Samir',
        4,
        'Good location and accurate timing. I received all results online the same evening.',
        '2026-07-11T09:45:00.000Z',
      ],
    ],
  },
  {
    id: 'precision-lab',
    name: 'Precision Lab',
    shortName: 'PL',
    city: 'Cairo',
    area: 'New Cairo',
    address: 'Medical Park, 90th Street, New Cairo',
    phone: '+20 2 2618 7044',
    rating: 4.7,
    reviewCount: 207,
    accreditation: 'ISO 9001 certified',
    turnaround: 'Express testing available',
    tone: 'mint',
    about:
      'Precision Lab focuses on fast, digitally delivered diagnostics with specialist oversight and convenient access for New Cairo residents.',
    facilities: ['Express results', 'Digital reports', 'Free parking'],
    services: [
      [
        'precision-lipid',
        'Lipid Profile',
        'Cholesterol and triglyceride assessment for cardiovascular health.',
        390,
        '3 hours',
        '10 hours fasting',
        true,
      ],
      [
        'precision-allergy',
        'Allergy Screening Panel',
        'A focused panel for common food and respiratory allergens.',
        2100,
        '48 hours',
        'No fasting required',
      ],
      [
        'precision-iron',
        'Iron & Ferritin Profile',
        'Iron stores and related markers for anemia assessment.',
        640,
        'Same day',
        'Morning sample preferred',
      ],
    ],
    reviews: [
      [
        'precision-review-1',
        'Nour Emad',
        5,
        'The express service was genuinely fast and the preparation notes were very helpful.',
        '2026-07-29T14:20:00.000Z',
      ],
      [
        'precision-review-2',
        'Youssef Ali',
        4,
        'Modern, organized, and easy to reach. Parking made the visit much simpler.',
        '2026-07-08T18:10:00.000Z',
      ],
    ],
  },
  {
    id: 'alexandria-clinical-lab',
    name: 'Alexandria Clinical Lab',
    shortName: 'AC',
    city: 'Alexandria',
    area: 'Smouha',
    address: '12 Fawzy Moaz Street, Smouha, Alexandria',
    phone: '+20 3 429 1182',
    rating: 4.8,
    reviewCount: 289,
    accreditation: 'ISO 15189 accredited',
    turnaround: 'Most results same day',
    tone: 'ocean',
    about:
      'Alexandria Clinical Lab offers accurate everyday diagnostics and family health packages from its central Smouha location.',
    facilities: ['Children-friendly room', 'Online reports', 'Home visits'],
    services: [
      [
        'alex-cbc',
        'Complete Blood Count',
        'Core blood cell measurements with clinical flags.',
        250,
        '2 hours',
        'No fasting required',
      ],
      [
        'alex-women',
        "Women's Wellness Package",
        'Blood, thyroid, iron, vitamin D, and metabolic screening.',
        1650,
        '24 hours',
        '8 hours fasting',
        true,
      ],
      [
        'alex-hormones',
        'Hormone Profile',
        'A focused reproductive and endocrine hormone panel.',
        1350,
        '24 hours',
        'Ask the lab about timing',
      ],
    ],
    reviews: [
      [
        'alex-review-1',
        'Dina Mostafa',
        5,
        'They were wonderful with my daughter and made the blood test feel much less stressful.',
        '2026-07-22T11:05:00.000Z',
      ],
      [
        'alex-review-2',
        'Karim Hany',
        5,
        'Professional service and a convenient Smouha location. The report arrived on time.',
        '2026-07-03T15:30:00.000Z',
      ],
    ],
  },
  {
    id: 'carecheck-laboratory',
    name: 'CareCheck Laboratory',
    shortName: 'CC',
    city: 'Giza',
    area: 'Sheikh Zayed',
    address: 'Arkan Plaza, Sheikh Zayed City, Giza',
    phone: '+20 2 3851 6630',
    rating: 4.6,
    reviewCount: 174,
    accreditation: 'National quality certified',
    turnaround: 'Results from 4 hours',
    tone: 'sage',
    about:
      'CareCheck makes preventive testing simple with carefully explained packages, comfortable sampling rooms, and secure digital delivery.',
    facilities: ['Private sampling rooms', 'Digital results', 'Free parking'],
    services: [
      [
        'care-sports',
        'Active Health Package',
        'CBC, kidney, liver, electrolytes, and vitamin D for active adults.',
        1720,
        '24 hours',
        '8 hours fasting',
        true,
      ],
      [
        'care-cardiac',
        'Cardiac Risk Profile',
        'Lipids, glucose, inflammation markers, and kidney function.',
        1180,
        'Same day',
        '10 hours fasting',
      ],
      [
        'care-b12',
        'Vitamin B12 Test',
        'Checks vitamin B12 levels related to energy and nerve health.',
        610,
        'Same day',
        'No fasting required',
      ],
    ],
    reviews: [
      [
        'care-review-1',
        'Farida Ashraf',
        5,
        'The private sampling room was comfortable and the team answered all my questions.',
        '2026-07-20T13:40:00.000Z',
      ],
      [
        'care-review-2',
        'Mahmoud Reda',
        4,
        'Easy booking and clear package details. I would use the laboratory again.',
        '2026-06-28T17:25:00.000Z',
      ],
    ],
  },
  {
    id: 'delta-diagnostics',
    name: 'Delta Diagnostics',
    shortName: 'DD',
    city: 'Mansoura',
    area: 'El Gomhouria Street',
    address: '86 El Gomhouria Street, Mansoura, Dakahlia',
    phone: '+20 50 221 9075',
    rating: 4.7,
    reviewCount: 198,
    accreditation: 'ISO 9001 certified',
    turnaround: 'Most results same day',
    tone: 'forest',
    about:
      'Delta Diagnostics provides dependable laboratory services for Mansoura families with experienced technicians and straightforward digital reporting.',
    facilities: [
      'Home sample collection',
      'WhatsApp reports',
      'Family packages',
    ],
    services: [
      [
        'delta-basic',
        'Basic Health Screen',
        'CBC, glucose, kidney, and liver screening.',
        890,
        'Same day',
        '8 hours fasting',
        true,
      ],
      [
        'delta-thyroid',
        'Thyroid Profile',
        'TSH, free T3, and free T4 hormone assessment.',
        650,
        'Same day',
        'No fasting required',
      ],
      [
        'delta-pcr',
        'PCR Infection Panel',
        'Targeted molecular testing based on the requested panel.',
        1250,
        '24-48 hours',
        'Depends on sample type',
      ],
    ],
    reviews: [
      [
        'delta-review-1',
        'Heba Khalil',
        5,
        'The home collection service was punctual and the report was sent directly to my phone.',
        '2026-07-25T08:50:00.000Z',
      ],
      [
        'delta-review-2',
        'Mostafa Gamal',
        4,
        'Friendly technicians, fair prices, and clear instructions before the test.',
        '2026-07-06T19:00:00.000Z',
      ],
    ],
  },
] as const;
